import Navigation from "@/components/Navigation";
import { QueryProvider } from "@/providers/QueryProvider";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "./providers/SessionProvider";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <NextAuthSessionProvider>
          <QueryProvider>
            <div className="min-h-screen bg-gray-100 flex flex-col gap-4">
              <Navigation />
              <main className="min-h-[calc(100vh-64px)] w-full mx-auto">
                {children}
              </main>
              <footer className="bg-blue-500 w-full">Footer</footer>
            </div>
          </QueryProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
